### ISSUE TITLE
Deploy Working Code 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#15]
- Test and Deploy working Code 

Replace .NET Nuget Package Loggy ( or Remove) 
Must Use a Package that will work on Linux 

-- Test Docker Image can build
-- Deploy Stack Using Rancher

### Jenkins:
-- Build Base Image (Add Packages to Base Image)
https://jenkins.navigatorglass.com/job/ImageGallery/job/ImageGallery-Client-Base-2/
https://jenkins.navigatorglass.com/job/ImageGallery/job/ImageGallery-Client-Build-2/

### Docker Hub
https://hub.docker.com/r/stuartshay/imagegallery-client/tags/

### Rancher
https://rancher.navigatorglass.com/env/1a5/apps/stacks/1st43/services/1s98/containers

### Note: The Current Docker Image is backed up. 
```
stuartshay/imagegallery-client:2.0-build-v1
```

**Comment by TerraVenil** [comment]
Please review https://github.com/stuartshay/ImageGallery.Client/pull/16.
Also you can check latest deployed container to **Rancher** https://rancher.navigatorglass.com/env/1a5/infra/containers/1i9952/ports
