### ISSUE TITLE
Album Photos

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#190]
### Albums List

- [x] 1.  Add Delete Functionality to Albums

    - [x]   OK/Cancel on Delete

![capture](https://user-images.githubusercontent.com/887805/48956176-863d7780-ef1f-11e8-9082-cbe6a2748e6a.PNG)

```
REST - DELETE (AlbumId)
http://localhost:8000/api/albums/b3b4fe1a-822b-4be9-b784-7499ceceab2b
```

![untitled](https://user-images.githubusercontent.com/887805/46987711-5a7ad680-d0c3-11e8-9972-0cb62f82e1c1.png)

### Album Details

 - [x] 2  Display Paging Photos  on ```http://localhost:8000/albums``` Album-View Page

![capture](https://user-images.githubusercontent.com/887805/48957151-e8e54200-ef24-11e8-894b-779dc8e4e6d0.PNG)

Add Paging 

![untitled](https://user-images.githubusercontent.com/887805/48957337-fea73700-ef25-11e8-827e-a5d4621040fe.png)

#### Postman Get 
```
L: Claire
P: password
http://localhost:8000/api/albums/images/list/10/1?id=6970fe3f-7446-42d2-9294-aa4feeca4e33
```
- [x]  Delete Image from Album 
      --  OK/Cancel on Delete

![untitled](https://user-images.githubusercontent.com/887805/48959852-606f9d00-ef36-11e8-9490-fae5c100f131.png)

- [x] 3   Breadcrumb  => Click on Link - Page Reloaded 

![untitled](https://user-images.githubusercontent.com/887805/48816994-6a18bb00-ed12-11e8-9361-f390c661ba2a.png)

**Comment by stuartshay** [comment]
Added Delete Image from Album API Call

**Comment by iobodianskyi** [comment]
Done. Also updated HttpClient for Angular. Implemented in branch album-photos

**Comment by stuartshay** [comment]
Looks Good & Thanks !!!!
