### ISSUE TITLE
Selenium - Test Setup

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#27]
The Project uses .NET Core a working example has been setup in the following project 
Use the page object model, to reduce code duplication

#### Note: The Project only needs to run tests for the Remote Site

![untitled](https://user-images.githubusercontent.com/887805/35783610-268c7b06-09d8-11e8-8e44-ae6809df5df0.png)

.NET Core Version 2.0
Driver: ChromeDriver
Remote Testing Site:  https://imagegallery-client.informationcart.com/

Working Test 
```
ImageGallery.Client.Test.UI.Selenium.ShouldLoadApplicationPage_SmokeTest()
```

- [ ] 1 Create a Test that will successfully login using the following User Accounts

```
Login: Claire  P: password  - (All Rights)
Login: Frank  P: password   - (Basic User)
```
Failure Test 

```
Login: Invalid  P: Invalid
```

![untitled](https://user-images.githubusercontent.com/887805/35783797-4c892aae-09db-11e8-9965-b00ebf454da3.png)

- [ ] 2 Create a Test that will validate the correct menu is displayed

Login: Claire  P: password  - (All Rights)

![untitled](https://user-images.githubusercontent.com/887805/35783822-e6e816e6-09db-11e8-8390-fc5e7510d63d.png)

Login: Frank  P: password   - (Basic User)

![untitled](https://user-images.githubusercontent.com/887805/35783833-47f1e9ee-09dc-11e8-8a4c-36b889a4d211.png)

**Comment by rtaum** [comment]
Commit https://github.com/stuartshay/ImageGallery.Client/commit/7bc51fe6f69f1ac6b9bf90d7f9ac0b5f9a8a1173 addresses this issue.
