### ISSUE TITLE
NG - Image Crop

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#305]
Add Image Cropper to Edit Image Page 

### Sample Package (Any Package or Library is ok) 
https://www.npmjs.com/package/ngx-image-cropper

Demo
https://stackblitz.com/edit/image-cropper

![untitled](https://user-images.githubusercontent.com/887805/48960701-f4446780-ef3c-11e8-84bc-1e5e638cfd8c.png)

### Sample Layout
Angle - Bootstrap Admin Template
http://themicon.co/theme/angle/v4.0/angular/forms/cropper

### API Call
![capture](https://user-images.githubusercontent.com/887805/48963434-2adfa980-ef60-11e8-9937-6d1609fa26b8.PNG)

Display Image URL from JSON Results  

![untitled](https://user-images.githubusercontent.com/887805/48963448-7d20ca80-ef60-11e8-8b0b-3ae72dfa666c.png)

Submit Croped Image for Update

#### Note Server Side Not Implemented (Will Return OK)

![capture](https://user-images.githubusercontent.com/887805/48964729-e104bc80-ef7b-11e8-977b-b38180fe6c2c.PNG)

**Comment by iobodianskyi** [comment]
I cannot get image base64 string due to CORS:

Access to image at 'https://imagegallery-api.informationcart.com/photos/3bb2a3ea-3df7-42e8-835b-970064205904.jpg' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by stuartshay** [comment]
I enabled the CORS Policy on the API Endpoint, Not Sure I did correctly or this will work.

I may need to code something so the image, is local to the server. 

For now the best solution copy the photo to folder and call the image locally, 
(Hard Coded same image for every page is fine)

**Comment by stuartshay** [comment]
Thanks this is good
