### ISSUE TITLE
NG - Width/Height Formating

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#339]
Photos can be 2 Sizes 
  (240 x 320) or (320x240)

Added Code to Display Width/Height 

#### Note the Photos in the list are not the correct scale will remove & updated as needed 

See Page 2 (Photo 016 - An image by Stuart)

![untitled](https://user-images.githubusercontent.com/887805/49556595-8f8cf380-f8d2-11e8-8bcc-cd7fa4798167.png)

### Current Width/Height Hardcoded 

![regular](https://user-images.githubusercontent.com/887805/49556605-9e73a600-f8d2-11e8-8f7e-393cf33e17cc.PNG)

**Comment by iobodianskyi** [comment]
Images with different ratio should fit layout like in this example?

![screen shot 31](https://user-images.githubusercontent.com/7642250/49689377-f572b880-fb28-11e8-834a-11307c40fb9d.png)

**Comment by stuartshay** [comment]
Anything that looks good, this is a good start

Would like to keep the photos the same size and the title and description lined up

**Comment by stuartshay** [comment]
I can change the photo size, if necessary, can hard code logic

**Comment by stuartshay** [comment]
Here is hardcoded logic 
https://github.com/stuartshay/ImageGallery.Client/blob/Auth/src/ImageGallery.Model/Models/Images/Image.cs

**Comment by stuartshay** [comment]
This Looks Good !!!
