### ISSUE TITLE
Gallery Edit Image 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#343]
- [x] 1 Get Photo From API

![untitled](https://user-images.githubusercontent.com/887805/49681132-b0884c80-fa6a-11e8-8caa-2b7f26413da6.png)

Note: Use Postman for testing if required (Will Not Work in Swagger)
Crop Image Save - Full Functional 👍 

- [ ] 2 Add Breadcrumb Navigation

![untitled](https://user-images.githubusercontent.com/887805/49681107-58514a80-fa6a-11e8-8de6-dbf890d489dd.png)

**Comment by iobodianskyi** [comment]
Is it possible to get from API image base64 string? 

I have issue with loading images from url for cropper. Due to security reasons browser don't allow loading from different domain.

Enabling supports cross-domain sharing is also may be solution (not sure, need to try)

**Comment by stuartshay** [comment]
This works in Postman, The Method has Authentication on it 

![capture](https://user-images.githubusercontent.com/887805/49703492-c82f1480-fbd3-11e8-978d-0389656fb2c8.PNG)

**Comment by stuartshay** [comment]
Should I try this
Base64 String

https://stackoverflow.com/questions/44860069/return-base64-encoded-images-directly-from-a-web-api-core-endpoint

**Comment by stuartshay** [comment]
Does this work, if so we can change

![capture](https://user-images.githubusercontent.com/887805/49710438-638dad00-fc07-11e8-8575-3300ba15ae8b.PNG)

**Comment by stuartshay** [comment]
If I need to Change the Format of the String, Hard Code the String Format in the Code. I can format as needed.

I want to keep the photo generated in the API, this way I can do pre-processing on the image, so the remote option is not something i want to use,
