### ISSUE TITLE
NG - Search Page Text State

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#362]
![untitled](https://user-images.githubusercontent.com/887805/49707477-6aadbe80-fbf9-11e8-957d-6059b9846a79.png)

3 Return to page (Search is Lost)

**Comment by iobodianskyi** [comment]
Search (and search page) should be saved even after page reload?

**Comment by stuartshay** [comment]
The search text should be stored in the local storages
