### ISSUE TITLE
NG - Edit Box Disable

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#363]
When Text Box is open, Click on Selection Should disable, Album Selection for item
I think this was working and got lost in merge

![capture](https://user-images.githubusercontent.com/887805/49711445-507ddb80-fc0d-11e8-9322-4e7cd65df294.PNG)

**Comment by stuartshay** [comment]
Make so if you click to close (cancel) the textbox edit it does not allow you to click into the album details

**Comment by iobodianskyi** [comment]
I think it's done. In latest Auth branch when you edit title or description navigation to album details is disabled.

**Comment by stuartshay** [comment]
This is Good, will add a new feature
