### ISSUE TITLE
NG - Album Tabs (Sorting)

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#392]
Add the Save to Album Sorting Tabs 
 -- Are there better ways to do this (Not Using Rest (GraphQL - Can Implemented/Setup)

 - [x] 1 - Determine JSON for Post (Save)

Mockup JSON  for Post (Will Implement what ever is easiest for NG Code)
 
 - [ ] 2 - Save to API   & Create Save Button

--  User Will Save and Submit Entire Document

**Comment by iobodianskyi** [comment]
The easiest way to make POST with array of ALL images with new orders, like this:
```
[
  {imageId: 'id_1', sort: 'newSortNumber'},
  {imageId: 'id_2', sort: 'newSortNumber'},
  ...
]
```

**Comment by stuartshay** [comment]
Added Sort Command (Will just return OK) - Code does not call API 
-- Would it be easier to return the update list too

I see that some of the methods are not consistent on my end, if anything that needs to be changed will do.

![untitled](https://user-images.githubusercontent.com/887805/50496353-27c35780-09fd-11e9-93ab-623fc4ceb930.png)

**Comment by stuartshay** [comment]
Implemented Album Image Sort 

![untitled](https://user-images.githubusercontent.com/887805/50551747-f2647700-0c53-11e9-9939-0778f571c038.png)

**Comment by stuartshay** [comment]
Great Work & THANKS !!!!
