### ISSUE TITLE
Selenium Tests - xUnit/ Selenium

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#46]
Complete the Following Tests, The Functionality does not yet exist to perform end to end testing, issues with  clearing the Auth Token

- [x] 1 Logout
``` 
BasicUserLogoutTest()
PrivilegedUserLogoutTest()
```
- [x] 2 Get Count of Total Photos

```
GetUsersTotalPhotosCountTest()
```

![untitled](https://user-images.githubusercontent.com/887805/36081435-ab3f73be-0f6c-11e8-8bd4-b7002a0300ed.png)

- [x] 3 Add Photo for Privileged User

Use Account

userName = "William";
password = "password";

```
PrivilegedUserAddPhoto()
```

- [ ] 4 Validate User Full Name on Login

See accounts.txt 

![capture](https://user-images.githubusercontent.com/887805/36389959-21a8c6ce-156f-11e8-8e69-76d450c41841.PNG)

**Comment by rtaum** [comment]
Point 1 is done

**Comment by rtaum** [comment]
I suggest to merge BasicUserLogoutTest and PrivilegedUserLogoutTest as only difference is the user name/password, code is the same.

**Comment by stuartshay** [comment]
Ya, this can be removed
