### ISSUE TITLE
F/IG-1 - Build Failure

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#5]
Unable to Build  Windows/Linux

### Windows
![capture](https://user-images.githubusercontent.com/887805/32587162-c72196b2-c4d4-11e7-81f9-208d6494e778.PNG)

### Linux 
![capture](https://user-images.githubusercontent.com/887805/32587191-ed460684-c4d4-11e7-813d-a6169af0fd1c.PNG)

**Comment by TerraVenil** [comment]
My fault forgot to delete node_modules folder and re-run `npm install` because I was deleted a lot of files/packages from template. Fixed. Please get latest.
