### ISSUE TITLE
Implementation of HttpClient which will be shared between multiple projects

### ISSUE THREAD

**Issue by TerraVenil** [stuartshay/ImageGallery.Client#58]
I would be ice to have some NuGet package like Navigator.HttpClient which can be shared between multiple projects this give us flexibility of sharing similar code and prevent duplication.

- https://github.com/stuartshay/NavigatorIdentity.UserManagement
- https://github.com/stuartshay/ImageGallery.Client
- https://github.com/stuartshay/NavigatorPhotoAgent.UI

**Comment by stuartshay** [comment]
I can document the steps 
We can use myget I have most this working in other projects should not be hard

**Comment by stuartshay** [comment]
See Project 
https://github.com/stuartshay/NavigatorIdentity.HttpClient/issues

**Comment by stuartshay** [comment]
Closing Issue, Moved to MyGet Project
