### ISSUE TITLE
F/IG-1 -SPA approach in Visual Studio

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#6]
The Project should use the same layout and structure as defined in the course 

Use the Existing Theme we are using for the F/1G-1 Branch (Create a new branch)

Course Link (Source Code)
https://github.com/DanWahlin/Angular-ASPNET-Core-CustomersService

- [ ] 1 Get Basic Functionality, Site Loads in Visual Studio (Use SPA approach)

**Comment by TerraVenil** [comment]
> Click About => Home (Site is Reloaded)
Currently we have to separate approches. First one related to server side rendering of HTML(.cshtml) and the second one SPA(client side) and they are not integrated. First of all we need to decided should we mix both approaches or to choose of them.

**Comment by stuartshay** [comment]
This is a new milestone. I started to watch this course and this might be the best way to do things 

Open to doing what is best,

https://app.pluralsight.com/library/courses/angular-aspnetcore-restful-services/table-of-contents
https://github.com/DanWahlin/Angular-ASPNET-Core-CustomersService
