### ISSUE TITLE
Loggly - C#/JS Logging 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/ImageGallery.Client#9]
https://www.loggly.com/
Will Provide Account Details, 

- [x]  1 - C# Server API Logging 

- [ ] 2 - js/client

**Comment by stuartshay** [comment]
Great, I will checkout tonight. 
For Loggly what is the account info, Feel Free to post L/P in this message, I will move to a paid account.

**Comment by TerraVenil** [comment]
Currently I hardocded token on Client/Backend sideif it willworks from your side I will extract to ClientSettings that you are be able to setup as variable.

**Comment by stuartshay** [comment]
Here is the account that is being used there is other stuff in the logs 

https://coredatastore.loggly.com
L: coredatastore
P: CoreDataStore2017

**Comment by stuartshay** [comment]
Got Some Basic Logging to Work
Still a work in progress

![capture](https://user-images.githubusercontent.com/887805/35479807-2a8e581a-03ce-11e8-94e9-573537d3c3aa.PNG)

**Comment by stuartshay** [comment]
Server Side Loggly Functional - See the Configuration Controller

![capture](https://user-images.githubusercontent.com/887805/35491541-15d3c5e8-0475-11e8-945b-00a70c019f5c.PNG)
